jobs:
  - name: golang-test
    type: runSh
    runtime:
      container: true
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14golall"
              imageTag: master
          script:
            - echo '[[ -s "/root/.gvm/scripts/gvm" ]] && source "/root/.gvm/scripts/gvm"'
            - gvm list
            - gvm use 1.4
            - go version
            - gvm use 1.7.6
            - go version
            - gvm use 1.8.7
            - go version
            - gvm use 1.9.6
            - go version
            - gvm use 1.10.2
            - go version
            
          
